version: 2
updates:
  - package-ecosystem: npm
    directory: /api
    schedule:
      interval: weekly
    groups:
      api-deps:
        patterns: ['*']
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      web-deps:
        patterns: ['*']
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /api
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /web
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
